config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Authenticated Routes
  authenticated :user do
    get '/' => 'home#index', as: :authenticated
    resources :reservations
    resources :pets

    namespace :employee do
      get '/' => 'home#index', as: :authenticated
      resources :reservations
      resources :pets
    end

    namespace :admin do
      get '/' => 'home#index', as: :authenticated
      resources :reservations
      resources :pets
    end
  end

  # Unauthenticated Routes
  root to: 'home#index', as: :unauthenticated
  get 'about', to: 'home#about', path: "/about"
  get 'contact', to: 'home#contact', path: "/contact"
  get 'help', to: 'home#help', path: "/help"
end

app/models/admin/reservation.rb
class Admin::Reservation < Reservation
end

app/models/employee/reservation.rb
class Employee::Reservation < Reservation
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/employee/reservations_controller.rb
class Employee::ReservationsController < Employee::AuthenticatedController
  before_action :set_employee_reservation, only: [:show, :edit, :update, :destroy]

  # GET /employee/reservations
  # GET /employee/reservations.json
  def index
    @employee_reservations = Employee::Reservation.all
  end

  # GET /employee/reservations/1
  # GET /employee/reservations/1.json
  def show
  end

  # GET /employee/reservations/new
  def new
    @employee_reservation = Employee::Reservation.new
  end

  # GET /employee/reservations/1/edit
  def edit
  end

  # POST /employee/reservations
  # POST /employee/reservations.json
  def create
    @employee_reservation = Employee::Reservation.new(employee_reservation_params)

    respond_to do |format|
      if @employee_reservation.save
        format.html { redirect_to @employee_reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @employee_reservation }
      else
        format.html { render :new }
        format.json { render json: @employee_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee/reservations/1
  # PATCH/PUT /employee/reservations/1.json
  def update
    respond_to do |format|
      if @employee_reservation.update(employee_reservation_params)
        format.html { redirect_to @employee_reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_reservation }
      else
        format.html { render :edit }
        format.json { render json: @employee_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee/reservations/1
  # DELETE /employee/reservations/1.json
  def destroy
    @employee_reservation.destroy
    respond_to do |format|
      format.html { redirect_to employee_reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_reservation
      @employee_reservation = Employee::Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_reservation_params
      params[:employee_reservation]
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < AuthenticatedController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:start_datetime, :end_datetime, :commited)
    end
end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/employee/reservations_helper.rb
module Employee::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.datetime_select :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br>
    <%= f.datetime_select :end_datetime %>
  </div>
  <div class="field">
    <%= f.label :commited %><br>
    <%= f.check_box :commited %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Start datetime</th>
      <th>End datetime</th>
      <th>Commited</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.start_datetime %></td>
        <td><%= reservation.end_datetime %></td>
        <td><%= reservation.commited %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start datetime:</strong>
  <%= @reservation.start_datetime %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @reservation.end_datetime %>
</p>

<p>
  <strong>Commited:</strong>
  <%= @reservation.commited %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>